# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Subledger
email: support@subledger.com
description: Subledger is a set of powerful APIs that allow you to quickly build the accounting part of your app.
baseurl: ""
url: "http://subledger.dev"
exclude: [ '_site/', '_ignore/', 'README.md']

# Build
markdown: kramdown

#Other
timezone: America/Los_Angeles

#Disqus.com Variables
comments:
